general:
  data_base_dir: /app/data
  version: 1.0
  description: configuration for Bamf NNUnet Kidney segmentation in 3D Slicer (nrrd to nifti)

execute:
- NrrdImporter
- NiftiConverter
- NNUnetRunner
- BamfProcessorRunner
- JsonSegExporter
- DataOrganizer

modules:
  NrrdImporter:
    input_dir: input_data
    input_file_name: image.nrrd

  JsonSegExporter:
    segment_id_meta_key: roi
    targets:
    - nifti:mod=seg-->[basename]

  NNUnetRunner:
    nnunet_task: Task779_Kidneys_KIRC
    nnunet_model: 3d_fullres
    roi: Kidney+NEOPLASM_MALIGNANT_PRIMARY,KIDNEY+CYST

  BamfProcessorRunner:

  DataOrganizer:
    targets:
    - nifti:mod=seg-->[basename]
    - json:mod=seg-->segdef.json