general:
  data_base_dir: /app/data
  version: 1.0
  description: SPIDER baseline segment vertebrae in Sagittal Spine MRI (dicom to mha segmentation)
  
execute:
- DicomImporter
- MhaConverter
- SpiderBaselineRunner
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta:
      mod: mr

  MhaConverter:
    engine: panimg

  DataOrganizer:
    targets:
      - mha:mod=seg-->[i:sid]/spider_baseline_vertebrae_segmentation.mha
