general:
  data_base_dir: /app/data
  version: 1.0
  description: SPIDER baseline segment vertebrae in Sagittal Spine MRI (mha to mha segmentation)
  
execute:
- FileStructureImporter
- SpiderBaselineRunner
- DataOrganizer

modules:
  FileStructureImporter:
    input_dir: 'input_data'
    structures:
      - $patientID@instance/images/sagittal-spine-mr-segmentation/mr.mha@mha:mod=mr
    import_id: patientID

  DataOrganizer:
    targets:
      - mha:mod=seg-->[i:patientID]/spider_baseline_vertebrae_segmentation.mha
