general:
  data_base_dir: /app/data
  version: 1.0
  description: LungMask segmentation default (dicom to dicom)

execute:
- FileStructureImporter
- NiftiConverter
- LungMaskRunner
- JsonSegExporter
- DataOrganizer

modules:
  FileStructureImporter:
    structures: 
    - image.nrrd@instance@nrrd:mod=ct

  LungMaskRunner:
    batchsize: 32

  JsonSegExporter:
    segment_id_meta_key: roi
    targets:
    - nifti:mod=seg-->[basename]

  DataOrganizer:
    targets:
    - nifti:mod=seg-->[basename]
    - json:mod=seg-->segdef.json