general:
  data_base_dir: /app/data
  version: 1.0.0
  description: LobeSegmentation workflow for 3D Slicer (nrrd to nifti)
  
execute:
- FileStructureImporter
- MhaConverter
- LobeSegmentationRunner
- NiftiConverter
- JsonSegExporter
- DataOrganizer

modules:
  FileStructureImporter:
    structures: 
    - image.nrrd@instance@nrrd:mod=ct

  NiftiConverter:
    in_datas: mha:mod=seg

  JsonSegExporter:
    targets:
    - nifti:mod=seg-->[basename]

  DataOrganizer:
    targets:
    - nifti:mod=seg-->[basename]
    - json-->segdef.json