general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf NNUnet MR Liver segmentation (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- NNUnetRunner
- BamfProcessorRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NiftiConverter:
    in_datas: dicom:mod=mr
    engine: plastimatch
    
  NNUnetRunner:
    in_data: nifti:mod=mr
    nnunet_task: Task822_Liver_AMD
    nnunet_model: 3d_fullres
    roi: LIVER

  DsegConverter:
    source_segs: nifti:mod=seg
    target_dicom: dicom:mod=mr
    model_name: Bamf NNUnet MR Liver
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/bamf_nnunet_mr_liver.seg.dcm