general:
  data_base_dir: /app/data
  version: 1.0
  description: Slicer Dev 

execute:
- FileStructureImporter
- ThresholdingRunner
- JsonSegExporter
- DataOrganizer

modules:
  FileStructureImporter:
    structures: 
    - image.nrrd@instance@nrrd:mod=ct

  ThresholdingRunner:
    TH: 300 
    roi_label: HEART
  
  JsonSegExporter:
    targets:
    - nrrd:mod=seg-->[basename]
  
  DataOrganizer:
    base: output_data
    targets:
    - nrrd:mod=seg-->[basename]
    - json:mod=seg-->segdef.json