general:
  data_base_dir: /app/data
  version: 1.0
  description: "default configuration for CaSuSt dicom to dicom"

execute:
- DicomImporter
- NiftiConverter
- NNUnetRunner
- CasustRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunner:
    folds: all
    nnunet_task: Task400_OPEN_HEART_1FOLD
    nnunet_model: 3d_lowres
    roi: HEART

  CasustRunner:
    test_time_augmentation: 0

  DsegConverter:
    model_name: CaSuSt
    source_segs: [nrrd:mod=seg, nifti:mod=seg]
    skip_empty_slices: True
  
  DataOrganizer:
    targets:
    - dicomseg:mod=seg-->[i:sid]/CaSuSt.seg.dcm