general:
  data_base_dir: /app/data
  version: 1.0.0
  description: 3D Slicer configuration for CaSuSt (nrrd to nrrd)

execute:
- NrrdImporter
- NiftiConverter
- NNUnetRunner
- CasustRunner
- JsonSegExporter
- DataOrganizer

modules:
  NrrdImporter:
    input_dir: input_data
    input_file_name: image.nrrd

  NNUnetRunner:
    folds: all
    nnunet_task: Task400_OPEN_HEART_1FOLD
    nnunet_model: 3d_lowres
    roi: HEART

  CasustRunner:
    test_time_augmentation: 0

  JsonSegExporter:
    segment_id_meta_key: roi
    targets:
    - nrrd:mod=seg-->[d:roi].nrrd
    - nifti:mod=seg-->[d:roi].nii.gz

  DataOrganizer:
    targets:
    - nrrd:mod=seg-->[d:roi].nrrd
    - nifti:mod=seg-->[d:roi].nii.gz
    - json:mod=seg-->segdef.json