general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for NNUnet Abdominal Organs at Risk segmentation (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- NNUnetRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunner:
    nnunet_task: Task017_AbdominalOrganSegmentation
    nnunet_model: 3d_lowres
    roi: SPLEEN,RIGHT_KIDNEY,LEFT_KIDNEY,GALLBLADDER,ESOPHAGUS,LIVER,STOMACH,AORTA,INFERIOR_VENA_CAVA,PORTAL_AND_SPLENIC_VEIN,PANCREAS,RIGHT_ADRENAL_GLAND,LEFT_ADRENAL_GLAND
    
  DsegConverter:
    source_segs: nifti:mod=seg
    model_name: NNUnet Thoracic OAR
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/nnunet_abdominal_oar.seg.dcm