general:
  data_base_dir: /app/data
  version: 1.0
  description: configuration for NNUnet Liver segmentation  in 3D Slicer (nrrd to nifti)

execute:
- NrrdImporter
- NiftiConverter
- NNUnetRunner
- JsonSegExporter
- DataOrganizer

modules:
  NrrdImporter:
    input_dir: 'input_data'
    input_file_name: 'image.nrrd'

  JsonSegExporter:
    segment_id_meta_key: roi
    targets:
    - nifti:mod=seg-->[basename]

  NNUnetRunner:
    nnunet_task: 'Task003_Liver'
    nnunet_model: '3d_lowres'
    roi: LIVER,LIVER+NEOPLASM_MALIGNANT_PRIMARY

  DataOrganizer:
    targets:
    - nifti:mod=seg-->[basename]
    - json:mod=seg-->segdef.json