general:
  data_base_dir: /app/data
  version: 1.0
  description: Tiger challenge winner LB2 (dicom:sm to json with Tils score)

execute:
- DicomImporter
- TiffPanImgConverter
- TigerLB2Runner
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: sm

  DataOrganizer:
    target_dir: output_data
    require_data_confirmation: true
    targets:
      - json-->[i:sid]/gc_tiger_lb2_tils_score.json
