general:
  data_base_dir: /app/data
  
modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: ct

  TiffImporter:
    source_dir: input_data
