general:
  data_base_dir: /app/data
  version: 1.0
  description: Ordinary Differential Equations algorithm for segmentation of individual colon glands (dicom to mha)
  
execute:
- DicomImporter
- MhaConverter
- OdeColonGlandsSegmentationRunner
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: wsi

  MhaConverter:
    engine: panimg

  DataOrganizer:
    targets:
      - mha:mod=seg-->[i:sid]/gc_ode_colon_glands.mha
