general:
  version: 1.0
  data_base_dir: /app/data
  description: configuration for nnuner pancreas model that includes probability masks as part of the export

execute:
  - DicomImporter
  - NiftiConverter
  - NNUnetRunner
  - DsegConverter
  - DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: ct

  NNUnetRunner:
    input_data_type: nifti:mod=ct
    nnunet_task: Task007_Pancreas
    nnunet_model: 3d_lowres
    export_prob_maps: True
    roi: PANCREAS,PANCREAS+NEOPLASM_MALIGNANT_PRIMARY
    prob_map_segments: [Background, Pancreas, Pancreatic_cancer]
    
  DsegConverter:
    #source_segs: [nifti:mod=seg]
    #json_config_path: /app/models/nnunet_pancreas/config/dseg.json
    source_segs: [nifti:mod=seg:roi=*]
    model_name: NNUnet Pancreas
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - nifti:mod=ct-->[i:sid]/image.nii.gz
    - nifti:mod=seg-->[i:sid]/pancreas.nii.gz
    - dicomseg:mod=seg-->[i:sid]/pancreas.seg.dcm
    - nrrd:mod=prob_mask-->[i:sid]/prob_masks/[path]