general:
  version: 1.0
  data_base_dir: /app/data
  description: 3D Slicer configuration for nnuner pancreas model

execute:
  - NrrdImporter
  - NiftiConverter
  - NNUnetRunner
  - JsonSegExporter
  - DataOrganizer

modules:

  NrrdImporter:
    input_dir: input_data
    input_file_name: image.nrrd

  NNUnetRunner:
    input_data_type: nifti:mod=ct
    nnunet_task: Task007_Pancreas
    nnunet_model: 3d_lowres
    export_prob_maps: False
    roi: PANCREAS,PANCREAS+NEOPLASM_MALIGNANT_PRIMARY
    
  JsonSegExporter:
    segment_id_meta_key: roi
    targets:
    - nifti:mod=seg-->[basename]

  DataOrganizer:
    targets:
    - nifti:mod=seg-->[basename]
    - json:mod=seg-->segdef.json