general:
  data_base_dir: /app/data
  version: 1.0.0
  description: default configuration for Platipy (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- PlatipyRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  DsegConverter:
    model_name: Platipy
    body_part_examined: CHEST
    source_segs: [nifti:mod=seg]
    skip_empty_slices: True

  DataOrganizer:
   targets:
   - nifti:mod=ct-->[i:sid]/image.nii.gz
   - dicomseg:mod=seg-->[i:sid]/Platipy.seg.dcm