general:
  data_base_dir: /app/data
  version: 1.0.0
  description: run platipy pipeline in MRunner (3D Slicer extension)

execute:
- FileStructureImporter
- NiftiConverter
- PlatipyRunner
- JsonSegExporter
- DataOrganizer

modules:
  FileStructureImporter:
    structures: 
    - image.nrrd@instance@nrrd:mod=ct

  JsonSegExporter:
    targets:
    - nifti:mod=seg-->[d:roi].nii.gz
    
  DataOrganizer:
    targets:
    - nifti:mod=seg-->[d:roi].nii.gz
    - json-->segdef.json
