general:
  data_base_dir: /app/data
  version: 1.0
  description: AutoPET False Positive Reduction nnUNet algorithm (dicom to dicom)

execute:
- FileStructureImporter
- NiftiConverter
- TciaDicomProcessor
- DataOrganizer

modules:
  FileStructureImporter:
    input_dir: 'input_data'
    structures:
      - $sid@instance/re:.*::/re:.*-GK.*::@dicom:mod=ct
      - $sid/re:.*::/re:.*-PET.*::@dicom:mod=pt
    import_id: sid

  NiftiConverter:
    engine: plastimatch
    allow_multi_input: true
    converted_file_name: '[basename].nii.gz'
    in_datas: dicom:mod=ct|pt

  DsegConverter:
    model_name: GCAutoPETfpr
    target_dicom: dicom:mod=pt
    source_segs: [mha:mod=seg:roi=*]
    skip_empty_slices: True
    segment_id_meta_key: roi
    body_part_examined: WHOLEBODY

  DataOrganizer:
    targets:
      - nifti:mod=pt-->[i:sid]/pt.nii.gz
      - nifti:mod=ct:resampled=true-->[i:sid]/ct_res.nii.gz
