general:
  data_base_dir: /app/data
  version: 1.0
  description: AutoPET False Positive Reduction nnUNet algorithm (dicom to dicom)

execute:
- FileStructureImporter
- MhaConverter
- AutoPETRunner
- DataOrganizer
- DsegConverter

modules:
  FileStructureImporter:
    input_dir: 'input_data'
    structures:
      - $sid@instance/re:.*::/re:.*-GK.*::@dicom:mod=ct
      - $sid/re:.*::/re:.*-PET.*::@dicom:mod=pt
    import_id: sid

  MhaConverter:
    engine: panimg
    allow_multi_input: True

  DsegConverter:
    model_name: GCAutoPETfpr
    target_dicom: dicom:mod=ct
    source_segs: [mha:mod=seg:roi=*]
    skip_empty_slices: True
    segment_id_meta_key: roi
    body_part_examined: WHOLEBODY

  DataOrganizer:
    targets:
      - mha:mod=seg-->[i:sid]/gc_autopet_fpr.seg.mha
      - dicomseg:mod=seg-->[i:sid]/gc_autopet_fpr.seg.dcm
