general:
  data_base_dir: /app/data
  version: 1.0
  description: AutoPET False Positive Reduction nnUNet algorithm (dicom to dicom)

execute:
- DicomImporter
- MhaConverter
- AutoPETRunner
- DataOrganizer
- DsegConverter

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
      meta:
        mod: '%Modality'

  MhaConverter:
    backend: panimg

  DsegConverter:
    model_name: GCAutoPETfpr
    target_dicom: dicom:mod=ct
    source_segs: [mha:mod=seg:roi=*]
    skip_empty_slices: True
    json_config_path: /app/models/gc_autopet_fpr/dseg.json

  DataOrganizer:
    targets:
      - mha:mod=seg-->[i:sid]/gc_autopet_fpr.seg.mha
      - dicomseg-->[i:sid]/gc_autopet_fpr.seg.dcm
